grafana:
  service:
    type: ClusterIP
  adminPassword: CHANGE_ME
  sidecar:
    dashboards:
      enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec: null
