apiVersion: v1
kind: Service
metadata:
  name: pod-con-pvc-svc
  namespace: dev
spec:
  selector:
    app: pod-con-pvc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080
  type: NodePort
