apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Coincide con la etiqueta en el Deployment de Nginx
  ports:
    - protocol: TCP
      port: 80        # Puerto del servicio
      targetPort: 80  # Puerto en el contenedor de Nginx
  type: ClusterIP    # El servicio es accesible solo dentro del clúster

